id: sysprefs_time_server_configure
title: "Configured to use an authorized time server"
discussion: |
  Only approved time servers should be configured for use.
check: |
  /usr/sbin/systemsetup -getnetworktimeserver | /usr/bin/awk -F ": " '{print $2}'
result:
  string: "time-a.nist.gov,time-b.nist.gov"
fix: |
  [source,bash]
  ----
  /usr/sbin/systemsetup -setnetworktimeserver "time-a.nist.gov,time-b.nist.gov"
  ----
references:
  cce:
    - CCE-84846-5
  cci: 
    - CCI-001891
    - CCI-002046
  800-53r4: 
    - AU-8(1)(a)
    - AU-8(1)(b)
  srg: 
    - SRG-OS-000355-GPOS-00143
    - SRG-OS-000356-GPOS-00144
  disa_stig: 
    - AOSX-14-000014
macOS:
  - "10.15"
tags:
  - cnssi-1253
  - fisma-moderate
  - fisma-high
  - STIG
mobileconfig: false
mobileconfig_info: