id: os_ssh_max_sessions_configure
title: "Configure SSH to limit the number of concurrent SSH sessions to 10"
discussion: |
  The SSH deamon should be configured to allow only 10 concurrent SSH sessions to the system.

  NOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.
check: |
  /usr/bin/grep -c "MaxSessions 10" /etc/ssh/sshd_config 
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/sed -i.bak 's/^[\#]*MaxSessions.*/MaxSessions 10/' /etc/ssh/sshd_config; /bin/launchctl kickstart -k system/com.openssh.sshd
  ----
references:
  cce:
    - CCE-84797-0
  cci:
    - CCI-000054
  800-53r4:
    - AC-10
  srg:
    - SRG-OS-000027-GPOS-00008
  disa_stig:
    - AOSX-14-000050
macOS:
  - "10.15"
tags:
  - fisma-high
  - STIG
mobileconfig: false
mobileconfig_info: